/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  homePage?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  navigation?: Array<{
    label?: string
    page?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'page'
    }
    externalUrl?: string
    _type: 'navItem'
    _key: string
  }>
  social?: Array<{
    label?: string
    url?: string
    _type: 'socialLink'
    _key: string
  }>
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  year?: number
  hero?: Figure
  video?: VideoEmbed
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Figure)
    | ({
        _key: string
      } & VideoEmbed)
  >
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  seo?: {
    metaTitle?: string
    metaDescription?: string
  }
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Figure)
    | ({
        _key: string
      } & VideoEmbed)
  >
}

export type VideoEmbed = {
  _type: 'videoEmbed'
  url?: string
  title?: string
}

export type Figure = {
  _type: 'figure'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  caption?: string
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        blank?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & Figure)
  | ({
      _key: string
    } & VideoEmbed)
>

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | SiteSettings
  | Project
  | Page
  | VideoEmbed
  | Figure
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ../src/lib/sanityQueries.ts
// Variable: allPageSlugsQuery
// Query: *[_type == "page" && defined(slug.current)]{ "slug": slug.current }
export type AllPageSlugsQueryResult = Array<{
  slug: string | null
}>
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  title,  "slug": slug.current,  seo{metaTitle, metaDescription},  content}
export type PageBySlugQueryResult = {
  title: string | null
  slug: string | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
  } | null
  content: Array<
    | ({
        _key: string
      } & Figure)
    | ({
        _key: string
      } & VideoEmbed)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
  > | null
} | null
// Variable: allProjectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type AllProjectSlugsQueryResult = Array<{
  slug: string | null
}>
// Variable: projectsIndexQuery
// Query: *[_type == "project"]|order(year desc, title asc){  title,  "slug": slug.current,  year,  hero}
export type ProjectsIndexQueryResult = Array<{
  title: string | null
  slug: string | null
  year: number | null
  hero: Figure | null
}>
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current == $slug][0]{  title,  "slug": slug.current,  year,  hero,  video,  body}
export type ProjectBySlugQueryResult = {
  title: string | null
  slug: string | null
  year: number | null
  hero: Figure | null
  video: VideoEmbed | null
  body: Array<
    | ({
        _key: string
      } & Figure)
    | ({
        _key: string
      } & VideoEmbed)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h2' | 'h3' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
  > | null
} | null
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  title,  "homeSlug": homePage->slug.current,  navigation[]{    label,    "pageSlug": page->slug.current,    externalUrl  },  social[]{label, url}}
export type SiteSettingsQueryResult = {
  title: string | null
  homeSlug: string | null
  navigation: Array<{
    label: string | null
    pageSlug: string | null
    externalUrl: string | null
  }> | null
  social: Array<{
    label: string | null
    url: string | null
  }> | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "page" && defined(slug.current)]{ "slug": slug.current }': AllPageSlugsQueryResult
    '*[_type == "page" && slug.current == $slug][0]{\n  title,\n  "slug": slug.current,\n  seo{metaTitle, metaDescription},\n  content\n}': PageBySlugQueryResult
    '*[_type == "project" && defined(slug.current)]{ "slug": slug.current }': AllProjectSlugsQueryResult
    '*[_type == "project"]|order(year desc, title asc){\n  title,\n  "slug": slug.current,\n  year,\n  hero\n}': ProjectsIndexQueryResult
    '*[_type == "project" && slug.current == $slug][0]{\n  title,\n  "slug": slug.current,\n  year,\n  hero,\n  video,\n  body\n}': ProjectBySlugQueryResult
    '*[_type == "siteSettings"][0]{\n  title,\n  "homeSlug": homePage->slug.current,\n  navigation[]{\n    label,\n    "pageSlug": page->slug.current,\n    externalUrl\n  },\n  social[]{label, url}\n}': SiteSettingsQueryResult
  }
}
